---
title: 'Basic concepts in matrix algebra'
author: "Stefan McKinnon Høj-Edwards & Peter Sørensen"
date: "`r Sys.Date()`"
output:
  bookdown::pdf_document2:
    citation_package: natbib
    number_sections: yes
    includes:
      in_header: preamble.tex
  html_document:
    number_sections: yes
    includes:
      in_header: mathjax_header.html
  word_document: default
bibliography: [qg2021.bib, book.bib, packages.bib]
link-citations: yes
---

This appendix supplies some general matrix algebra that is useful in these notes.
Proof of these, as well as additional explanation, can be found in e.g.\ \citet{SearleMatrix}, \citet{SearleVC} and/or \citet{Knight2008}. And Schaeffer's EuropeNotes p. 194.

The matrix $V$ is the square variance-covariance matrix $V = ZGZ' + D$.


\bigskip
\noindent
Denoting the derivative of the matrix:
\begin{equation}
  \matr{V}_i = \frac{\partial \matr{V}}{\partial \sigma^2_i} =  
  \begin{cases} 
  	\matr{D}_n & \text{when} ~\sigma^2_i = \sigma^2_e \\ 
  	\matr{ZGZ}' & \text{when} ~\sigma^2_i = \sigma^2_g 
  	\end{cases}
\end{equation}  	


The derivative of the first quadratic from with respect to $X$:
\begin{equation}
  \frac{\partial (\vect{y} - \matr{X}\bfbeta)'\matr{V}(\vect{y} - \matr{X}\bfbeta)}{\partial \matr{X}} = -2 \matr{X'V}(\vect{y} - \matr{X}\bfbeta)
\end{equation} 

The derivative of the \emph{inverse} matrix
\begin{equation}
  \frac{\partial \matr{V}^{-1}}{\partial \sigma^2_i} = -\matr{V}^{-1} \matr{V}_i \matr{V}^{-1}
\end{equation}  

The derivative of the \emph{trace} of the matrix
\begin{equation}
  \frac{\partial \Tr(\matr{V})}{\partial \sigma^2_i} = \Tr(\matr{V}_i)
\end{equation}  

The derivative of the logarithm of the matrix' determinant:
\begin{equation}
  \frac{\partial \ln | \matr{V} |}{\partial \sigma^2_i} = \Tr(\matr{V}^{-1} \matr{V}_i)
\end{equation}


The derivative of the first and second quadratic forms, when taken with respect to $\sigma^2_i$:
\begin{subequations}
\begin{align}
  \frac{\partial (\vect{y} - \matr{X}\bfbeta)'\matr{V}(\vect{y} - \matr{X}\bfbeta)}{\partial \sigma^2_i} &= (\vect{y} - \matr{X}\bfbeta)' \matr{V}_i (\vect{y} - \matr{X}\bfbeta) \\
  \frac{\partial (\vect{y} - \matr{X}\bfbeta)'\matr{V}^{-1}(\vect{y} - \matr{X}\bfbeta)}{\partial \sigma^2_i} &= -(\vect{y} - \matr{X}\bfbeta)' \matr{V}^{-1} \matr{V}_i \matr{V}^{-1} (\vect{y} - \matr{X}\bfbeta)
\end{align}  
%
and the derivative of the logarithm of the determinant of the second quadratic form:
\begin{equation}
  \frac{\partial \ln | \matr{X}' \matr{V}^{-1} \matr{X} |}{\partial \sigma^2_i} = \Tr( (\matr{X}' \matr{V}^{-1} \matr{X})^{-1} \matr{X}' \matr{V}^{-1} \matr{V}_i \matr{V}^{-1} \matr{X})
\end{equation}
but also \citep[p.\ 21]{Knight2008}:
\begin{align*}
  &\frac{\partial \ln |\matr{V}|}{\partial \sigma^2_i} + \frac{\partial \ln | \matr{X}' \matr{V}^{-1} \matr{X} |}{\partial \sigma^2_i} \\
  &= \Tr(\matr{V}^{-1} \matr{V}_i) - \Tr( (\matr{X}' \matr{V}^{-1} \matr{X})^{-1} \matr{X}' \matr{V}^{-1} \matr{V}_i \matr{V}^{-1} \matr{X}) \\
  &= \Tr(\matr{V}^{-1} \matr{V}_i -  (\matr{X}' \matr{V}^{-1} \matr{X})^{-1} \matr{X}' \matr{V}^{-1} \matr{V}_i \matr{V}^{-1} \matr{X}) \\
  &= \Tr(\matr{P} \matr{V}_i)
  .
\end{align*}  
\end{subequations}

A \emph{projection matrix}, $P$ can be defined as
\begin{equation}
  \matr{P} = \matr{V}^{-1} - \matr{V}^{-1} \matr{X} (\matr{X}'\matr{V}^{-1}\matr{X})^{-1} \matr{X}' \matr{V}^{-1}
  \label{eq:app.matrix.P}
\end{equation}
%
and has following nice properties:
\begin{align}
  \matr{PX} &= 0 \\
  \matr{P}\vect{y} &= \matr{V}^{-1}(\vect{y}-\matr{X}\betahat), ~ \text{where} \label{eq:app:Py} \\
  \betahat &= (\matr{X}'\matr{V}^{-1}\matr{X})^{-1}\matr{X'V}^{-1}\vect{y} \\
  \hat{\matr{P}}\vect{y} &= \ehat
\end{align}  


The derivative of the projection matrix:
\begin{equation}
  \frac{\partial \matr{P}}{\partial \sigma^2_i} = -\matr{P} \matr{V}_i \matr{P}
\end{equation}  


For traces, we have:
\begin{subequations}
\begin{equation}
  \Tr(\matr{P}) = \vect{y}'\matr{PP}\vect{y}
\end{equation}
or
\begin{equation}
  \Tr(\matr{PV}_i) = \vect{y}'\matr{PV}_i\matr{P}\vect{y}
  .
\end{equation}
\end{subequations}

%\section*{Some forms}

In \eqref{eq:gblup.blup} on page \pageref{eq:gblup.blup}, the form $\matr{ZGZ}'$ is used. 
The following is the result if we consider a very simple example with two animals, where the first has two observations and the second only one.
\begin{align}
  \vect{y} &= \mu + \matr{Z}\vect{g} + \vect{e} \notag \\
  \matr{Z} &= 
  	\begin{bmatrix}
  	  1 & 0 \\ 1 & 0 \\ 0 & 1
  	\end{bmatrix} 
  & \matr{G} = \begin{bmatrix}
  		g_{11} & g_{12} \\ g_{21} & g_{22}
  	\end{bmatrix} \notag \\
  \matr{ZGZ}' &= 
  	\begin{bmatrix}
	    g_{11} & g_{11} & g_{12} \\
	    g_{11} & g_{11} & g_{12} \\
	    g_{21} & g_{21} & g_{22}
    \end{bmatrix}  
  & \matr{ZZ}' =
    \begin{bmatrix}
      1 & 1 & 0 \\ 1 & 1 & 0 \\ 0 & 0 & 1
    \end{bmatrix} 
  \label{eq:app:zgz}
\end{align}


\section{Derivation of mean and variance of quadratic forms}
\label{sec:app:quad.forms}

If we assume that $\vect{y} \sim N(\mu, \matr{V})$ then \citep[p.\ 466]{SearleVC}
\begin{align*}
  \E(\vect{y}'\matr{Q}\vect{y}) &= \Tr(\matr{QV}) + \mu'\matr{Q}\mu \\
  \Var(\vect{y}'\matr{Q}\vect{y}) &= 2 \Tr(\matr{QVQV}) + 4\mu'\matr{QVQ}\mu
\end{align*}
The quadratic form $\vect{y}'\matr{Q}\vect{y}$ has a non-central 
$\chi^2$ distribution with $rank(\matr{Q})$ degrees of freedom and non-central parameter $\half \mu'\matr{Q}\mu$,
if and only if $\matr{QV}$ is idempotent (Theorem S2, p.\ 467, \citealp{SearleVC}).
When $\matr{QV}$ is idempotent, then $\matr{QVQV}=\matr{QV} \Rightarrow \Tr(\matr{QVQV}) = \Tr(\matr{QV})$, and $\Tr(\matr{QV}) = rank(\matr{QV})$.




Because $\mu = 0$, $\matr{V}=\matr{I}$, and $\matr{Q}=\matr{V}^\half_0\matr{MV}^\half_0$ (where $\matr{M} = \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z}' \matr{V}^{-1}_0$), the expectation and variance of the quadratic form are  
\begin{align*}
  \E(\vect{y}'\matr{Q}\vect{y}) &= \Tr(\matr{Q}) \\
  &= \Tr\left( \half \matr{V}^\half_0 \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z'V}^{-1}_0 \matr{V}^\half_0 \right) \\
  &= \half \Tr\left(\matr{V}^\half_0 \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z'V}^{-1}_0 \matr{V}^\half_0 \right) \\
  &= \half \Tr\left(\matr{V}^{-1}_0 \matr{ZG}_i\matr{Z}' \right)
\end{align*}
and
\begin{align*}
  \Var(\vect{y}'\matr{Q}\vect{y}) &= 2 \Tr(\matr{QQ}) \\
  &= 2 \Tr \left( \left[ \half \matr{V}^\half_0 \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z' V}^{-1}_0 \matr{V}^\half_0\right]\left[ \half \matr{V}^\half_0 \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z' V}^{-1}_0 \matr{V}^\half_0\right]  \right) \\
  &= \half \Tr \left( \left[ \matr{V}^\half_0 \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z' V}^{-1}_0 \matr{V}^\half_0\right] \left[ \matr{V}^\half_0 \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z' V}^{-1}_0 \matr{V}^\half_0\right]   \right) \\
  &= \half \Tr \left(  \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z' V}^{-1}_0 \matr{ZG}_i\matr{Z' V}^{-1}_0 \matr{V}^\half_0 \matr{V}^\half_0   \right) \\
  &= \half \Tr \left( \matr{V}^{-1}_0 \matr{ZG}_i\matr{Z' V}^{-1}_0 \matr{ZG}_i\matr{Z}' \right).
\end{align*}  


We can further elaborate that $\vect{y}'\matr{Q}\vect{y}$ is $\chi^2$ distributed with $\Tr(\matr{Q})$ degrees of freedom under the conditions above.

